### ISSUE TITLE
The nodom/server side functionality does not seem to work.

### ISSUE THREAD

**Issue by robballou** [pakastin/redom#67]
I'm trying to setup tests for a project and running into issues with the nodom/server side functionality. To simplify a bit, using the example from this project and nodom fails when I directly run it as well:

```javascript
const { Document, render } = require('nodom');
const document = new Document();
const { el, mount } = require('redom');

mount(document.body, el('h1', 'Hello world!'));

console.log(render(document.body));
```

I get the following:

```
/home/jdoe/Desktop/redom-test/node_modules/redom/dist/redom.js:11
document && (style = document.createElement('p').style);
^

ReferenceError: document is not defined
    at /home/jdoe/Desktop/redom-test/node_modules/redom/dist/redom.js:11:1
    at attached (/home/jdoe/Desktop/redom-test/node_modules/redom/dist/redom.js:2:65)
    at Object.<anonymous> (/home/jdoe/Desktop/redom-test/node_modules/redom/dist/redom.js:5:2)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```

With:

* node 7.10.0.
* redom 2.6.1

**Comment by pakastin** [comment]
It should work like that, it's not long since I tried it and it worked.

I'll take a look at it this evening.

You could try
```js
const document = global.document = new Document()
```
..before requiring RE:DOM.

**Comment by pakastin** [comment]
Yeah, the `global.document` is the answer – I fixed the example:
https://github.com/pakastin/nodom
